#!/bin/bash
echo "alias ll='ls -al'" >> ~/.bashrc
source ~/.bashrc

mv /home/work/github.com/liziwei01/go-liziwei01-appui/commit-msg /home/work/github.com/liziwei01/go-liziwei01-appui/.git/hooks/
chmod u+x /home/work/github.com/liziwei01/go-liziwei01-appui/.git/hooks/commit-msg

hostname -i

go run /home/work/github.com/liziwei01/go-liziwei01-appui/main.go
